services:
  - type: web
    name: obsidian-remote
    env: docker
    repo: https://github.com/harshadprs/obsidian-remote
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CUSTOM_PORT
        value: "8080"
      - key: CUSTOM_USER
        value: abc
      - key: PASSWORD
        sync: false
      - key: TZ
        value: Asia/Kolkata
      - key: DOCKER_MODS
        value: linuxserver/mods:universal-git
    domains:
      - note.harshad.eu.org
